name: Databricks Notebook Deployment

on: 
  push:
    branches:
      - feature
  workflow_dispatch:

jobs:
  deploy-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli
        pip install --upgrade databricks-cli

    - name: Authenticate Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        echo "Authenticating Databricks CLI..."
        echo $DATABRICKS_HOST
        echo $DATABRICKS_TOKEN
        databricks workspace ls /  

    - name: Deploy Notebooks
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        echo "Deploying Notebooks to Databricks..."
        databricks workspace import_dir --overwrite "Test-Notebooks" "/Notebooks/"
