name: Deploy to UAT
 
on: 
  workflow_dispatch:
 
jobs:
 
  deploy-notebooks:
    environment:
      name: DEV
    runs-on: windows-latest
    # runs-on: [self-hosted, STG] 
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
 
 
    - name: Install Databricks CLI
      run: |
        pip install databricks-cli
        pip install --upgrade databricks-cli

        
    - name: Authenticate Databricks CLI
      env:
        DATABRICKS_HOST: ${{ vars.DATABRICKS_URL }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        echo "Authenticating Databricks CLI..."
        echo $DATABRICKS_HOST
        echo $DATABRICKS_TOKEN
        databricks workspace ls /  

        
    # - name: Authenticate Databricks CLI
    #   env:
    #     DATABRICKS_HOST: ${{ vars.DATABRICKS_URL }}
    #     DATABRICKS_TOKEN: ${{ secrets.PAT_TOKEN }}
    #   run: |
    #     echo [DEFAULT] > ~\.databrickscfg
    #     echo host=${{ vars.DATABRICKS_HOST }} >> ~\.databrickscfg
    #     echo token=${{ secrets.DATABRICKS_TOKEN }} >> ~\.databrickscfg
    #     echo jobs-api-version=2.1 >> ~\.databrickscfg
    #     databricks workspace ls /  

 
    - name: Deploy Notebooks to Databricks workspace
      env:
        DATABRICKS_HOST: ${{ vars.DATABRICKS_URL }}
        DATABRICKS_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        databricks workspace import_dir --overwrite "${{github.workspace}}/Development/" "/Shared"
